name: Table1

on:
  workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.3.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
            cache-version: 2
            packages: |
              any::dplyr
              any::xtable
      - name: run claims
        working-directory: './src'
        run: |
          source("create_table1.R")
        shell: Rscript {0} 
